In [2]:
from PIL import Image
import glob, os
import numpy as np
import cv2

In [107]:
faces=[]
unrolled_faces=[]
labels= []
# orl_faces = os.chdir("..")
# os.chdir("orl_faces")
print(os.getcwd()) 
dire="A:\\term8\\Pattern Recognition\\Assignments\\Assignment 1\\New face\\Face-Recognition\\orl_faces"
# os.chdir(dir)
i=0
for folder in os.listdir(dire):
    face_dir=os.path.join(dire,folder) 
    labels.append(folder)
#     print(face_dir)
    os.chdir(face_dir)
    for face in os.listdir(face_dir):
        fc=os.path.join(face_dir,face)
        faces.append(cv2.imread(fc,0))
#         print(cv2.imread(fc,0).size)
        unrolled_faces.append(np.array(cv2.imread(fc,0)).flatten())
#         print(fc)
        
# Uncomment the following block if u want to show the images, each image is alternated by a keyboard click

#         cv2.imshow('image',lis[i])
#         i+=1
#         cv2.waitKey(0)
#         cv2.destroyAllWindows()
#         print(lis)
print(faces[0].shape)
# print(faces[0][0].size)#400 pics
# print(faces)
# print(labels)
# print(unrolled_faces)
npfaces=np.array(unrolled_faces)
print('fasel 3shan 5ater rowan')
print(npfaces[399].shape)
print(labels)


A:\term8\Pattern Recognition\Assignments\Assignment 1\New face\Face-Recognition\orl_faces\s9
(112, 92)
fasel 3shan 5ater rowan
(10304,)
['s1', 's10', 's11', 's12', 's13', 's14', 's15', 's16', 's17', 's18', 's19', 's2', 's20', 's21', 's22', 's23', 's24', 's25', 's26', 's27', 's28', 's29', 's3', 's30', 's31', 's32', 's33', 's34', 's35', 's36', 's37', 's38', 's39', 's4', 's40', 's5', 's6', 's7', 's8', 's9']


In [110]:
test = npfaces[::2]
train = npfaces[1::2]

    
print(test)
print( "      test up     ")
print(train)
print("       train up  ")
print(npfaces)


[[ 48  49  45 ...  47  46  46]
 [ 60  60  62 ...  32  34  34]
 [ 63  53  35 ...  41  10  24]
 ...
 [114 110 112 ...  93  89  86]
 [113 112 111 ...  87  87  89]
 [111 114 112 ...  88  86  92]]
      test up     
[[ 34  34  33 ...  37  40  33]
 [ 39  44  53 ...  29  26  29]
 [ 64  76  80 ...  35  37  39]
 ...
 [110 109 111 ...  94  88  90]
 [112 109 116 ...  93  88  92]
 [110 112 113 ...  92  87  90]]
       train up  
[[ 48  49  45 ...  47  46  46]
 [ 34  34  33 ...  37  40  33]
 [ 60  60  62 ...  32  34  34]
 ...
 [112 109 116 ...  93  88  92]
 [111 114 112 ...  88  86  92]
 [110 112 113 ...  92  87  90]]
