In [1]:
from PIL import Image
import glob, os
import numpy as np
import cv2

In [5]:
faces=[]
unrolled_faces=[]
labels= []
# orl_faces = os.chdir("..")
# os.chdir("orl_faces")
print(os.getcwd()) 
dire="D:\Term 8\Pattern Recognition\Face Recognition Project\orl_faces"
# os.chdir(dir)
i=0
for folder in os.listdir(dire):
    face_dir=os.path.join(dire,folder) 
    labels.append(folder)
#     print(face_dir)
    os.chdir(face_dir)
    for face in os.listdir(face_dir):
        fc=os.path.join(face_dir,face)
        faces.append(cv2.imread(fc,0))
#         print(cv2.imread(fc,0).size)
        unrolled_faces.append(np.array(cv2.imread(fc,0)).flatten())
#         print(fc)
        
# Uncomment the following block if u want to show the images, each image is alternated by a keyboard click

#         cv2.imshow('image',lis[i])
#         i+=1
#         cv2.waitKey(0)
#         cv2.destroyAllWindows()
#         print(lis)
print(faces[0].shape)

npfaces=np.array(unrolled_faces)
print('fasel 3shan 5ater rowan')
print(npfaces[399].shape)
print(labels)


D:\Term 8\Pattern Recognition\Face Recognition Project\.ipynb_checkpoints
(112, 92)
fasel 3shan 5ater rowan
(10304,)
['s1', 's10', 's11', 's12', 's13', 's14', 's15', 's16', 's17', 's18', 's19', 's2', 's20', 's21', 's22', 's23', 's24', 's25', 's26', 's27', 's28', 's29', 's3', 's30', 's31', 's32', 's33', 's34', 's35', 's36', 's37', 's38', 's39', 's4', 's40', 's5', 's6', 's7', 's8', 's9']


In [7]:
test = npfaces[::2]
train = npfaces[1::2]

    
print(test)
print( "      test up     ")
print(train)
print("       train up  ")
print(npfaces)
print(labels)


[[ 48  49  45 ...  47  46  46]
 [ 60  60  62 ...  32  34  34]
 [ 63  53  35 ...  41  10  24]
 ...
 [114 110 112 ...  93  89  86]
 [113 112 111 ...  87  87  89]
 [111 114 112 ...  88  86  92]]
      test up     
[[ 34  34  33 ...  37  40  33]
 [ 39  44  53 ...  29  26  29]
 [ 64  76  80 ...  35  37  39]
 ...
 [110 109 111 ...  94  88  90]
 [112 109 116 ...  93  88  92]
 [110 112 113 ...  92  87  90]]
       train up  
[[ 48  49  45 ...  47  46  46]
 [ 34  34  33 ...  37  40  33]
 [ 60  60  62 ...  32  34  34]
 ...
 [112 109 116 ...  93  88  92]
 [111 114 112 ...  88  86  92]
 [110 112 113 ...  92  87  90]]
['s1', 's10', 's11', 's12', 's13', 's14', 's15', 's16', 's17', 's18', 's19', 's2', 's20', 's21', 's22', 's23', 's24', 's25', 's26', 's27', 's28', 's29', 's3', 's30', 's31', 's32', 's33', 's34', 's35', 's36', 's37', 's38', 's39', 's4', 's40', 's5', 's6', 's7', 's8', 's9']


In [85]:
s1 = train[0:5]
s10 = train[5:10]
s11 = train[10:15]
s12 = train[15:20]
s13 = train[20:25]
s14 = train[25:30]
s15 = train[30:35]
s16 = train[35:40]
s17 = train[40:45]
s18 = train[45:50]
s19 = train[50:55]
s2 = train[55:60]
s20 = train[60:65]
s21 = train[65:70]
s22 = train[70:75]
s23 = train[75:80]
s24 = train[80:85]
s25 = train[85:90]
s26 = train[90:95]
s27 = train[95:100]
s28 = train[100:105]
s29 = train[105:110]
s3 = train[110:115]
s30 = train[115:120]
s31 = train[120:125]
s32 = train[125:130]
s33 = train[130:135]
s34 = train[135:140]
s35 = train[140:145]
s36 = train[145:150]
s37 = train[150:155]
s38 = train[155:160]
s39 = train[160:165]
s4 = train[165:170]
s40 = train[170:175]
s5 = train[175:180]
s6 = train[180:185]
s7 = train[185:190]
s8 = train[190:195]
s9 = train[195:200]

Original_S = np.array([train[0:5],train[55:60],train[110:115],train[165:170],train[175:180]
,train[180:185],train[185:190],train[190:195],train[195:200],train[5:10],train[10:15],train[15:20],train[20:25],train[25:30],train[30:35]
,train[35:40],train[40:45],train[45:50],train[50:55],train[60:65],train[65:70],train[70:75],train[75:80],train[80:85],train[85:90]
,train[90:95],train[95:100],train[100:105],train[105:110],train[115:120],train[120:125],train[125:130],train[130:135],train[135:140]
,train[140:145],train[145:150],train[150:155],train[155:160],train[160:165],train[170:175]])

In [111]:
MuS=np.array([s1.mean(axis=0),s2.mean(axis=0),s3.mean(axis=0),s4.mean(axis=0),s5.mean(axis=0),s6.mean(axis=0),s7.mean(axis=0),s8.mean(axis=0),s9.mean(axis=0)
 ,s10.mean(axis=0),s11.mean(axis=0),s12.mean(axis=0),s13.mean(axis=0) ,s14.mean(axis=0),s15.mean(axis=0),s16.mean(axis=0),s17.mean(axis=0)
 ,s18.mean(axis=0),s19.mean(axis=0),s20.mean(axis=0),s21.mean(axis=0),s22.mean(axis=0),s23.mean(axis=0),s24.mean(axis=0),s25.mean(axis=0)
 ,s26.mean(axis=0),s27.mean(axis=0),s28.mean(axis=0),s29.mean(axis=0),s30.mean(axis=0),s31.mean(axis=0),s32.mean(axis=0),s33.mean(axis=0)
,s34.mean(axis=0),s35.mean(axis=0),s36.mean(axis=0),s37.mean(axis=0),s38.mean(axis=0),s39.mean(axis=0),s40.mean(axis=0)])

Mu= np.array(MuS.mean(axis=0))[np.newaxis]
print("Over All Mean is: ", Mu.T)


Over All Mean is:  [[86.265]
 [86.365]
 [86.795]
 ...
 [77.35 ]
 [77.915]
 [78.24 ]]


In [222]:
S_W=np.zeros((40,10304))
New_S=np.zeros((40,10304))

for i in range(40):

    New_S= np.dot(Original_S[i].T - MuS[i].reshape(10304,1),Original_S[i]-MuS[i])
    
for i in range(40):
    S_W+= New_S[i]

print(S_W)    

[[  3416.8   1884.4   1383.2 ... -15389.2 -16564.  -14237.2]
 [  3416.8   1884.4   1383.2 ... -15389.2 -16564.  -14237.2]
 [  3416.8   1884.4   1383.2 ... -15389.2 -16564.  -14237.2]
 ...
 [  3416.8   1884.4   1383.2 ... -15389.2 -16564.  -14237.2]
 [  3416.8   1884.4   1383.2 ... -15389.2 -16564.  -14237.2]
 [  3416.8   1884.4   1383.2 ... -15389.2 -16564.  -14237.2]]


In [223]:
# New_S = Original_S - Mu.T

# for i in range(40):
#     New_S = Original_S[i] - Mu
#     S_T = np.array(Original_S[i].T)

# New_S_T= S_T - Mu.T

Mu=Mu.reshape(10304,1)
SB=np.zeros((40,10304))
S_B=np.zeros((40,10304))

for i in range(40):
    Bee= 5 *np.dot((MuS[i].reshape(10304,1) - Mu),(MuS[i].reshape(10304,1) - Mu).T)
    S_B+= Bee[i]
#     print(Bee[i])
    
# for i in B:    
#     SB+= i

# print("       ")
# print("       ")
# print("       ")
# print(Bee[0])

print(S_B)
# print(SB)

# New_S_T.dot()

# print(MuS - Mu)
# print("The Transpose")
# print((MuS - Mu).T)
# print(MuS[0])
# print(MuS[1])
# print(Mu)

[[160448.233875 159364.956375 159013.216625 ... -18684.25875
  -16919.737375 -13550.938   ]
 [160448.233875 159364.956375 159013.216625 ... -18684.25875
  -16919.737375 -13550.938   ]
 [160448.233875 159364.956375 159013.216625 ... -18684.25875
  -16919.737375 -13550.938   ]
 ...
 [160448.233875 159364.956375 159013.216625 ... -18684.25875
  -16919.737375 -13550.938   ]
 [160448.233875 159364.956375 159013.216625 ... -18684.25875
  -16919.737375 -13550.938   ]
 [160448.233875 159364.956375 159013.216625 ... -18684.25875
  -16919.737375 -13550.938   ]]
