In [102]:
from PIL import Image
import glob, os
import numpy as np
import cv2
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [2]:
faces=[]
unrolled_faces=[]
labels= []
# orl_faces = os.chdir("..")
# os.chdir("orl_faces")
print(os.getcwd()) 
dire="D:\Term 8\Pattern Recognition\Face Recognition Project\orl_faces"
# os.chdir(dir)
i=0
for folder in os.listdir(dire):
    face_dir=os.path.join(dire,folder) 
    labels.append(folder)
#     print(face_dir)
    os.chdir(face_dir)
    for face in os.listdir(face_dir):
        fc=os.path.join(face_dir,face)
        faces.append(cv2.imread(fc,0))
#         print(cv2.imread(fc,0).size)
        unrolled_faces.append(np.array(cv2.imread(fc,0)).flatten())
#         print(fc)
        
# Uncomment the following block if u want to show the images, each image is alternated by a keyboard click

#         cv2.imshow('image',lis[i])
#         i+=1
#         cv2.waitKey(0)
#         cv2.destroyAllWindows()
#         print(lis)
print(faces[0].shape)

npfaces=np.array(unrolled_faces)
print('fasel 3shan 5ater rowan')
print(npfaces[399].shape)
print(labels)


D:\Term 8\Pattern Recognition\Face Recognition Project
(112, 92)
fasel 3shan 5ater rowan
(10304,)
['s1', 's10', 's11', 's12', 's13', 's14', 's15', 's16', 's17', 's18', 's19', 's2', 's20', 's21', 's22', 's23', 's24', 's25', 's26', 's27', 's28', 's29', 's3', 's30', 's31', 's32', 's33', 's34', 's35', 's36', 's37', 's38', 's39', 's4', 's40', 's5', 's6', 's7', 's8', 's9']


In [100]:
test = npfaces[::2]
train = npfaces[1::2]

    
print(test)
print( "      test up     ")
print(train)
print("       train up  ")
print(npfaces)
print(labels)

train_labels = np.array([])

for lbl in labels:
      for i in range(0,5):
            train_labels = np.append(train_labels,lbl)

print(train_labels)

[[ 48  49  45 ...  47  46  46]
 [ 60  60  62 ...  32  34  34]
 [ 63  53  35 ...  41  10  24]
 ...
 [114 110 112 ...  93  89  86]
 [113 112 111 ...  87  87  89]
 [111 114 112 ...  88  86  92]]
      test up     
[[ 34  34  33 ...  37  40  33]
 [ 39  44  53 ...  29  26  29]
 [ 64  76  80 ...  35  37  39]
 ...
 [110 109 111 ...  94  88  90]
 [112 109 116 ...  93  88  92]
 [110 112 113 ...  92  87  90]]
       train up  
[[ 48  49  45 ...  47  46  46]
 [ 34  34  33 ...  37  40  33]
 [ 60  60  62 ...  32  34  34]
 ...
 [112 109 116 ...  93  88  92]
 [111 114 112 ...  88  86  92]
 [110 112 113 ...  92  87  90]]
['s1', 's10', 's11', 's12', 's13', 's14', 's15', 's16', 's17', 's18', 's19', 's2', 's20', 's21', 's22', 's23', 's24', 's25', 's26', 's27', 's28', 's29', 's3', 's30', 's31', 's32', 's33', 's34', 's35', 's36', 's37', 's38', 's39', 's4', 's40', 's5', 's6', 's7', 's8', 's9']
['s1' 's1' 's1' 's1' 's1' 's10' 's10' 's10' 's10' 's10' 's11' 's11' 's11'
 's11' 's11' 's12' 's12' 's12' 's12' 's12

In [4]:
s1 = train[0:5]
s10 = train[5:10]
s11 = train[10:15]
s12 = train[15:20]
s13 = train[20:25]
s14 = train[25:30]
s15 = train[30:35]
s16 = train[35:40]
s17 = train[40:45]
s18 = train[45:50]
s19 = train[50:55]
s2 = train[55:60]
s20 = train[60:65]
s21 = train[65:70]
s22 = train[70:75]
s23 = train[75:80]
s24 = train[80:85]
s25 = train[85:90]
s26 = train[90:95]
s27 = train[95:100]
s28 = train[100:105]
s29 = train[105:110]
s3 = train[110:115]
s30 = train[115:120]
s31 = train[120:125]
s32 = train[125:130]
s33 = train[130:135]
s34 = train[135:140]
s35 = train[140:145]
s36 = train[145:150]
s37 = train[150:155]
s38 = train[155:160]
s39 = train[160:165]
s4 = train[165:170]
s40 = train[170:175]
s5 = train[175:180]
s6 = train[180:185]
s7 = train[185:190]
s8 = train[190:195]
s9 = train[195:200]

Original_S = np.array([train[0:5],train[55:60],train[110:115],train[165:170],train[175:180]
,train[180:185],train[185:190],train[190:195],train[195:200],train[5:10],train[10:15],train[15:20],train[20:25],train[25:30],train[30:35]
,train[35:40],train[40:45],train[45:50],train[50:55],train[60:65],train[65:70],train[70:75],train[75:80],train[80:85],train[85:90]
,train[90:95],train[95:100],train[100:105],train[105:110],train[115:120],train[120:125],train[125:130],train[130:135],train[135:140]
,train[140:145],train[145:150],train[150:155],train[155:160],train[160:165],train[170:175]])

In [9]:
MuS=np.array([s1.mean(axis=0),s2.mean(axis=0),s3.mean(axis=0),s4.mean(axis=0),s5.mean(axis=0),s6.mean(axis=0),s7.mean(axis=0),s8.mean(axis=0),s9.mean(axis=0)
 ,s10.mean(axis=0),s11.mean(axis=0),s12.mean(axis=0),s13.mean(axis=0) ,s14.mean(axis=0),s15.mean(axis=0),s16.mean(axis=0),s17.mean(axis=0)
 ,s18.mean(axis=0),s19.mean(axis=0),s20.mean(axis=0),s21.mean(axis=0),s22.mean(axis=0),s23.mean(axis=0),s24.mean(axis=0),s25.mean(axis=0)
 ,s26.mean(axis=0),s27.mean(axis=0),s28.mean(axis=0),s29.mean(axis=0),s30.mean(axis=0),s31.mean(axis=0),s32.mean(axis=0),s33.mean(axis=0)
,s34.mean(axis=0),s35.mean(axis=0),s36.mean(axis=0),s37.mean(axis=0),s38.mean(axis=0),s39.mean(axis=0),s40.mean(axis=0)])

Mu= np.array(MuS.mean(axis=0))[np.newaxis]
print("Over All Mean is: ", Mu.T)
print(MuS.shape)
print(MuS[0].reshape(10304,1))

Over All Mean is:  [[86.265]
 [86.365]
 [86.795]
 ...
 [77.35 ]
 [77.915]
 [78.24 ]]
(40, 10304)
[[44. ]
 [48.4]
 [51.4]
 ...
 [35.6]
 [36.6]
 [36. ]]


In [10]:
S_W=np.zeros((10304,10304))

for i in range(40):

    New_S= np.array(np.dot(Original_S[i].T - MuS[i].reshape(10304,1),Original_S[i]-MuS[i]))
    S_W+=New_S


print(S_W.shape)    
print(Original_S.shape)
print(MuS.shape)
print(New_S.shape)
print(S_W.shape)
print(S_W)

(10304, 10304)
(40, 5, 10304)
(40, 10304)
(10304, 10304)
(10304, 10304)
[[24423.2 23833.4 23526.  ...  -964.  -1262.6 -2064.4]
 [23833.4 25988.8 24427.8 ... -1819.4 -3178.  -2968.4]
 [23526.  24427.8 26166.8 ...  -158.  -2224.  -4336.4]
 ...
 [ -964.  -1819.4  -158.  ... 91074.8 63122.2 37822.6]
 [-1262.6 -3178.  -2224.  ... 63122.2 77461.2 54698.2]
 [-2064.4 -2968.4 -4336.4 ... 37822.6 54698.2 81746.8]]


In [11]:

S_B=np.zeros((10304,10304))

for i in range(40):
    Bee= np.array(5 *np.dot((MuS[i].reshape(10304,1) - Mu.T),(MuS[i] - Mu)))
    S_B+=Bee


print(Bee.shape)
print(S_B.shape)
print(S_B)




(10304, 10304)
(10304, 10304)
[[229647.755 229781.255 225540.865 ... -18199.55  -22264.895 -18137.32 ]
 [229781.255 230657.555 226154.165 ... -18978.15  -23072.795 -18861.12 ]
 [225540.865 226154.165 222227.795 ... -19050.65  -22795.485 -18884.76 ]
 ...
 [-18199.55  -18978.15  -19050.65  ... 310058.7   313472.75  311491.6  ]
 [-22264.895 -23072.795 -22795.485 ... 313472.75  321528.355 317164.88 ]
 [-18137.32  -18861.12  -18884.76  ... 311491.6   317164.88  319319.68 ]]


In [15]:
S_W_inv= np.linalg.inv(S_W)
print(S_W_inv)

[[-3.13864104e+10 -7.04226409e+10  5.63765748e+10 ... -2.62539077e+10
  -8.95079287e+09 -1.01392930e+10]
 [ 5.64095327e+10  1.22568051e+11 -1.03110574e+11 ...  3.61841037e+10
   1.36325491e+10  3.83596921e+09]
 [-3.42524203e+10 -5.67230384e+10  4.92962483e+10 ... -1.83706536e+10
  -1.85879615e+10 -1.33716590e+09]
 ...
 [ 5.86382547e+08 -2.55017198e+09  2.83971143e+09 ...  2.45248360e+09
  -5.56588898e+08 -1.42457244e+09]
 [-3.17129722e+09 -6.29133025e+09  4.48358704e+09 ... -1.93362809e+09
  -1.37407422e+08  1.52361215e+08]
 [ 3.71215049e+09  5.12608324e+09 -3.40547498e+09 ...  3.02182169e+09
   1.43869775e+09 -8.03478045e+08]]


In [16]:
eig_vals, eig_vecs = np.linalg.eig(S_W_inv.dot(S_B))

In [41]:
print(eig_vals)
print("       vectors are     :    ")
print(eig_vecs)

[-2.56685601e+17+0.00000000e+00j  5.13935798e+16+1.24693309e+17j
  5.13935798e+16-1.24693309e+17j ... -1.19988772e+00+1.02890161e+00j
 -1.19988772e+00-1.02890161e+00j  1.39854116e+00+0.00000000e+00j]
       vectors are     :    
[[-0.07049804+0.00000000e+00j  0.06880213-3.64899738e-03j
   0.06880213+3.64899738e-03j ... -0.0054103 +2.52842214e-03j
  -0.0054103 -2.52842214e-03j  0.00081588+0.00000000e+00j]
 [ 0.14635891+0.00000000e+00j -0.09678724+0.00000000e+00j
  -0.09678724-0.00000000e+00j ...  0.00959356-1.56052403e-03j
   0.00959356+1.56052403e-03j -0.00605675+0.00000000e+00j]
 [-0.07847942+0.00000000e+00j  0.04258062-3.93916510e-03j
   0.04258062+3.93916510e-03j ...  0.00323135+6.30875161e-04j
   0.00323135-6.30875161e-04j -0.00688617+0.00000000e+00j]
 ...
 [ 0.00243155+0.00000000e+00j  0.00761877-2.85636279e-03j
   0.00761877+2.85636279e-03j ... -0.0020358 +1.26285336e-03j
  -0.0020358 -1.26285336e-03j -0.0015088 +0.00000000e+00j]
 [-0.00933056+0.00000000e+00j  0.00116957+3.850534

In [25]:
eig_vals.max()

(5.139357984241871e+16+1.246933086936298e+17j)

In [26]:
idx = eig_vals.argsort()[::-1]
eigenValues = eig_vals[idx]
eigenVectors = eig_vecs[:,idx]

print(eigenValues)

[ 5.13935798e+16+1.24693309e+17j  5.13935798e+16-1.24693309e+17j
  3.54280271e+16+0.00000000e+00j ... -2.95490588e+16-5.71742361e+15j
 -3.53441139e+16+0.00000000e+00j -2.56685601e+17+0.00000000e+00j]


In [29]:
print(eigenValues[0])
print(eigenValues[2])

(5.139357984241871e+16+1.246933086936298e+17j)
(3.5428027067978876e+16+0j)


In [77]:
top_eig=[]
top_vec=[]
for i in range(39):
    top_eig.append(eigenValues[i])
    top_vec.append(eigenVectors[i])
    
top_eig=np.array(top_eig)
top_vec=np.array(top_vec)
print(top_eig.shape)
print(top_vec.shape)
print(top_eig)
print(top_vec)

(39,)
(39, 10304)
[5.13935798e+16+1.24693309e+17j 5.13935798e+16-1.24693309e+17j
 3.54280271e+16+0.00000000e+00j 1.68281955e+16+1.01982983e+16j
 1.68281955e+16-1.01982983e+16j 9.04139703e+15+2.89547986e+16j
 9.04139703e+15-2.89547986e+16j 8.74640412e+15+3.31495456e+15j
 8.74640412e+15-3.31495456e+15j 4.83622470e+15+1.11030843e+14j
 4.83622470e+15-1.11030843e+14j 2.88292939e+15+5.02353848e+15j
 2.88292939e+15-5.02353848e+15j 2.77050128e+15+0.00000000e+00j
 1.37012890e+15+6.32133208e+14j 1.37012890e+15-6.32133208e+14j
 4.71012847e+14+3.10717094e+15j 4.71012847e+14-3.10717094e+15j
 2.13731695e+05+0.00000000e+00j 1.59674208e+04+0.00000000e+00j
 8.28040117e+03+0.00000000e+00j 6.04976865e+03+7.69017399e+03j
 6.04976865e+03-7.69017399e+03j 5.72833886e+03+0.00000000e+00j
 4.66705710e+03+0.00000000e+00j 4.63213523e+03+3.24282943e+03j
 4.63213523e+03-3.24282943e+03j 3.07488748e+03+6.09526302e+02j
 3.07488748e+03-6.09526302e+02j 2.68541582e+03+1.62210786e+03j
 2.68541582e+03-1.62210786e+03j 1.513

In [78]:
eig_pairs = [(np.abs(top_eig[i]), top_vec[:,i]) for i in range(len(top_eig))]

# eigv_sum = sum(top_eig)
# for i in range(40):
#     print('eigenvalue {0:}: {1:.2%}', top_eig[i], (top_vec[i]/eigv_sum).real)

eigv_sum = sum(top_eig)
for i,j in enumerate(eig_pairs):
    print('eigenvalue {0:}: {1:.2%}'.format(i+1, (j[0]/eigv_sum).real))

eigenvalue 1: 58.81%
eigenvalue 2: 58.81%
eigenvalue 3: 15.45%
eigenvalue 4: 8.58%
eigenvalue 5: 8.58%
eigenvalue 6: 13.23%
eigenvalue 7: 13.23%
eigenvalue 8: 4.08%
eigenvalue 9: 4.08%
eigenvalue 10: 2.11%
eigenvalue 11: 2.11%
eigenvalue 12: 2.53%
eigenvalue 13: 2.53%
eigenvalue 14: 1.21%
eigenvalue 15: 0.66%
eigenvalue 16: 0.66%
eigenvalue 17: 1.37%
eigenvalue 18: 1.37%
eigenvalue 19: 0.00%
eigenvalue 20: 0.00%
eigenvalue 21: 0.00%
eigenvalue 22: 0.00%
eigenvalue 23: 0.00%
eigenvalue 24: 0.00%
eigenvalue 25: 0.00%
eigenvalue 26: 0.00%
eigenvalue 27: 0.00%
eigenvalue 28: 0.00%
eigenvalue 29: 0.00%
eigenvalue 30: 0.00%
eigenvalue 31: 0.00%
eigenvalue 32: 0.00%
eigenvalue 33: 0.00%
eigenvalue 34: 0.00%
eigenvalue 35: 0.00%
eigenvalue 36: 0.00%
eigenvalue 37: 0.00%
eigenvalue 38: 0.00%
eigenvalue 39: 0.00%


In [104]:
print(top_vec.shape)
print(train.shape)

LDA_train = np.real(train.dot(top_vec.T))
LDA_test = np.real(test.dot(top_vec.T))
print(LDA_train.shape)
print(LDA_test.shape)
print(LDA_train)

(39, 10304)
(200, 10304)
(200, 39)
(200, 39)
[[ 9.55955161e+02  4.30900937e+02  7.96558024e+02 ...  7.01318199e+01
  -5.01847128e+01  4.20915332e+02]
 [ 8.89822598e+02  5.20913891e+02  7.79935909e+02 ...  3.22601416e-01
  -1.62505011e+02  3.24571024e+02]
 [ 8.91752271e+02  6.77515998e+02  7.87423633e+02 ...  8.82532534e+01
  -1.26914969e+02  4.00016324e+02]
 ...
 [ 6.12074892e+02  8.05914918e+02  7.84039004e+02 ...  1.20850716e+01
   9.16847665e+00  3.34675699e+02]
 [ 5.98021134e+02  6.26850588e+02  6.28976125e+02 ... -4.57602440e+01
   2.53791911e+01  2.25213914e+02]
 [ 6.95843882e+02  7.38492452e+02  6.51025477e+02 ... -3.67421905e+01
   2.33703349e+01  2.80491377e+02]]


In [115]:
# KNN Classifier

clf = KNeighborsClassifier(n_neighbors = 1)

clf.fit(LDA_train, train_labels)
output_labels = clf.predict(LDA_test)
print(accuracy_score(output_labels,train_labels))




0.915
